srcdir = '.'
blddir = 'build'
VERSION = '0.0.5555'

# hello brilliant windows waf using person, make this go.

def set_options(opt):
  #opt.tool_options('compiler_cxx')

def configure(conf):
  #conf.check_tool('compiler_cxx')
  #conf.check_tool('node_addon')

def build(bld):
  #obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  #obj.target = 'serialport_freakish_whiteman'
  #obj.source = 'serialport_fraekish_whiteman.cc'
